version: '2'
services:
    salon-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/salon/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=salon
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
